name: CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: Upgrade build tools
        run: |
          python -m pip install --upgrade pip setuptools wheel

      - name: Install deps
        run: |
          pip install -r requirements.txt

      - name: Run tests
        env:
          MPLBACKEND: Agg
        run: |
          pytest -q

  # Simple CLI smoke test using the installed console script
  cli-smoke:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
      - run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt
          pip install -e .
          # Create tiny csv and run the CLI
          python - <<'PY'
          import numpy as np, tempfile, os, json, subprocess, sys
          d = tempfile.mkdtemp()
          p = os.path.join(d, "a2F.csv")
          om = np.array([80, 100, 120, 140, 160, 180, 200], float)
          a2f = np.array([0.5, 0.7, 1.0, 0.9, 0.8, 0.6, 0.4], float)
          np.savetxt(p, np.column_stack([om, a2f]), delimiter=",")
          out = os.path.join(d, "o.json")
          r = subprocess.run(["rtsc-eliashberg","--alpha2F_csv",p,"--mu_star","0.12","--json-out",out])
          print("exit", r.returncode)
          print("json exists:", os.path.exists(out))
          sys.exit(0 if r.returncode in (0,10) else 1)
          PY
