# Tools/modules to dynamically register into MCP
modules:
  - name: "plogic-pack"
    module: "mcp_agent.tools.plogic_bo"
    register: "register_toolset"
    enabled: true
    strict: true   # Production: fail fast on missing deps
